### ISSUE TITLE
Does not support .php files

### ISSUE THREAD

**Issue by fredemmott** [PranayAgarwal/vscode-hack#1]
PHP files starting with `<?hh` should be recognized as Hack

**Comment by fredemmott** [comment]
Works fine if I select 'Hack' from the bottom right corner, but doing that for each file is very annoying.

**Comment by fredemmott** [comment]
Heh, just noticed this is on the readme, sorry.

**Comment by PranayAgarwal** [comment]
Doubt I can fix this without VS Code changes, unfortunately. Tracked at https://github.com/Microsoft/vscode/issues/13782.

**Comment by mickhrmweb** [comment]
I solve this using the following settings:

```json
  "files.associations": {
    "*.php": "hack"
  }    
```

**Comment by bpasero** [comment]
@PranayAgarwal we did a change for the next release that will give an extension higher priority for providing language features compared to our built in ones (the related issue is https://github.com/Microsoft/vscode/issues/20074). As such, when I install the Hack extension into our insiders build (http://code.visualstudio.com/insiders) any `*.php` file that gets opened will be associated with `Hack` because your extension is [declaring](https://github.com/PranayAgarwal/vscode-hack/blob/master/package.json#L48) `*.php: hack`. 

Now, I see how this is not the same as fixing https://github.com/Microsoft/vscode/issues/10915 but it may be a workaround for the problem altogether. 

To clarify: can you handle (or do you want to handle) any PHP file, even if it does not have a `firstline` matching `^<\\?hh\\b.*$` ? Or in other words, is our new behaviour better or worse for your scenario?

**Comment by PranayAgarwal** [comment]
Thanks for the quick turnaround on this. Even though I don't wan't to handle all PHP files, the new behavior is still better for my scenario. I only added the `*.php` match because first line was not working. If I remove the `*.php` match from the config, will my extension still get precedence over `<?hh` files over the built-in PHP?

Ideally, though, I wish it was possible to configure the language match based on extension(s) AND first line, rather than OR.

**Comment by bpasero** [comment]
@PranayAgarwal you currently still need to register the PHP extension. I agree that the real solution is to be able to express extension AND first line.

**Comment by PranayAgarwal** [comment]
@bpasero what if the user also has another extension installed which also matches `*.php` files (e.g. php-intellisense). In that case, will hack get precedence (because it additionally has a first line match registered)?

**Comment by bpasero** [comment]
No, we do not have good handling enforcing this (it is related). The rule is first come (as on disk), first serve.

**Comment by PranayAgarwal** [comment]
It seems like this was fixed in a recent VS Code release (I'm not sure which one). Works for me now without an override, but could someone double check?

**Comment by fredemmott** [comment]
Yep, worked for me this morning.
